name: Tests

on:
  push:
   branches:
     - main
  pull_request:
    branches:
     - "*"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py_ver: ["3.8", "3.9"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.py_ver }}
    steps:
    - uses: actions/checkout@master
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.py_ver }}
        environment-file: env.yml
        activate-environment: ee
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info --all
        conda list
    - name: Installing ee
      shell: bash -l {0}
      run: |
        python -m pip install -e .
    - name: Running tests
      shell: bash -l {0}
      run: |
        pytest  tests \
                -vv \
                -n auto \
                --color=yes
